### ISSUE TITLE
Option to get string-based output

### ISSUE THREAD

**Issue by muodov** [adrianliaw/PyCuber#9]
Escape-sequences for coloring are nice for interactive programming, but not very friendly for automate tasks. Would be nice to have an option to disable color output and just return color strings like "red" or "orange". Or, even better, the ability to pass color mappings into constructor of the Cube class.

If you think it is a good idea, I can actually propose a pull request for this

**Comment by adrianliaw** [comment]
Cool! Just send me a pull request, and I'm happy to see that. Thanks a lot!
